### ISSUE TITLE
Resolve rip relatives

### ISSUE THREAD

**Issue by Symbai** [spazzarama/SharpDisasm#11]
Possible to add this feature?

**Comment by justinstenning** [comment]
Can you please provide an example of what you would be expecting (input + output).

**Comment by Symbai** [comment]
Input 64bit with code starting at 0x7FF648E4A9C5 :
`48 8B 0D 1C ED 01 00`

currently produces:
` mov rcx, [rip+0x1ed1c]`

with resolving rip relatives the output will be:
`mov rcx,[0x7FF648E696E8]`

In the CLI we cannot enter a  start address so you would have to do this in code.
