### ISSUE TITLE
Translate assembly code to hex code?

### ISSUE THREAD

**Issue by sesey** [spazzarama/SharpDisasm#21]
I thank everyone for the project.
How do I translate assembly code to hex code?

**Comment by justinstenning** [comment]
what do you mean by this? Do you mean compile ASM (in which case use a ASM compiler)? Or do you mean view machine code as hex (just convert binary to hex)?

**Comment by sesey** [comment]
I want to convert machine code to hex code.

**Comment by sesey** [comment]
I do not want to do this with the ASM compiler.
With the SharpDisasm library I want to convert the assembly code to hex code.
Can hex code conversion be done with Udi86 class?
Is this possible?

**Comment by Fonger** [comment]
As the name suggest, both SharpDiasm and udis86 are **Dis**assembler. So, NO

**Comment by sesey** [comment]
If disassembler can be done, assembler can also be done.

**Comment by justinstenning** [comment]
Yes, but not with a disassembler, for that you need a compiler/assembler
